In [2]:
import pandas as pd
import numpy as np
import scipy.io as sio
import os
import re
import source.load_mat_files as mat_fls

In [3]:
os.listdir()

['Test_Load_Transform.ipynb',
 '.DS_Store',
 'requirements.txt',
 'Untitled.ipynb',
 'Dockerfile',
 'source',
 'tests',
 'load_transform_data.ipynb',
 'docs',
 'loading_mat_file.ipynb',
 '.ipynb_checkpoints',
 'Data']

Load data: 

In [4]:
mat_contents = sio.loadmat('Data/Sub_01_locomotion_metrics_T2.mat')

The mat_contents object is a python dictionary:

In [5]:
type(mat_contents)

dict

There is information about the creation of the file in an entry specified by a key called __header__ : 

In [6]:
mat_contents['__header__']

b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Mon Apr  4 15:59:06 2022'

In [7]:
mat_contents['__version__']

'1.0'

There is another entry is specified by the key 'results' and it is a numpy array:

In [8]:
type(mat_contents['results'])

numpy.ndarray

The numpy array contains another numpy array which in turn contains an object of type numpy.void: 

In [9]:
type(mat_contents['results'][0])

numpy.ndarray

In [10]:
type(mat_contents['results'][0][0])

numpy.void

This object (mat_contents['results'][0][0]) then contains 15 elements and an attribute with information about 15 elements:

In [11]:
len(mat_contents['results'][0][0])

15

In [12]:
len(mat_contents['results'].dtype)

15

In [13]:
mat_contents['results'].dtype

dtype([('nfoot', 'O'), ('steps_tot', 'O'), ('WB_time', 'O'), ('Ngait_cycles', 'O'), ('gait_timestamps', 'O'), ('cadence_mean', 'O'), ('speed_mean', 'O'), ('speed_std', 'O'), ('slength_mean', 'O'), ('slength_std', 'O'), ('gtime_mean', 'O'), ('gtime_std', 'O'), ('speed_CV', 'O'), ('slength_CV', 'O'), ('gtime_CV', 'O')])

The elements in mat_contents['results'][0][0] are all numpy arrays, each of length 1 (it turns out, there is yet another numpy array inside this array of length 1 where you find the actual data):

In [26]:
for index in range(0, len(mat_contents['results'][0][0])):
    print('\n')
    print(index)
    print(type(mat_contents['results'][0][0][index]))
    print('length')
    print(len(mat_contents['results'][0][0][index]))



0
<class 'numpy.ndarray'>
length
1


1
<class 'numpy.ndarray'>
length
1


2
<class 'numpy.ndarray'>
length
1


3
<class 'numpy.ndarray'>
length
1


4
<class 'numpy.ndarray'>
length
1


5
<class 'numpy.ndarray'>
length
1


6
<class 'numpy.ndarray'>
length
1


7
<class 'numpy.ndarray'>
length
1


8
<class 'numpy.ndarray'>
length
1


9
<class 'numpy.ndarray'>
length
1


10
<class 'numpy.ndarray'>
length
1


11
<class 'numpy.ndarray'>
length
1


12
<class 'numpy.ndarray'>
length
1


13
<class 'numpy.ndarray'>
length
1


14
<class 'numpy.ndarray'>
length
1


One can have a look at the 15 arrays and the 15 information items about the arrays: 

In [31]:
mat_contents['results'][0][0][5]

array([[ 90.05229743, 103.29464096,  52.5003051 ,  61.26043554,
         58.46970686,  65.02735765,  79.35433467,  55.52923232,
         61.65209544,  58.54636887,  58.2352045 ,  60.8580735 ,
         78.67607821,  65.83321848,  59.1036802 ,  57.24532117,
         52.21608709,  54.8938333 ,  91.72904187, 142.94101948,
         55.68445476,  51.27669459,  89.81346633,  65.30896018,
         63.86792623,  56.49889049,  53.03939731,  52.92364139,
         51.01211255,  55.28914662,  73.11066938,  53.42862127,
         51.27126211,  77.90314946,  64.05432084,  58.15988079,
         58.38398366,  78.22980443,  53.9692733 ,  75.07096897,
         49.67904216,  64.37740699,  53.99647056,  66.52730404,
         57.03675272, 104.8808961 ,  98.8686801 ,  81.81054251,
         77.9988954 ,  78.71568042, 104.72023719,  89.81327895,
         64.38890702, 117.54488381, 192.31885961, 141.18895826,
         59.55944815,  46.02413015,  91.2136864 ,  51.99716813,
        109.6810936 ,  47.17729569,  82.

It is the array inside the array that contains the actual data, so you need to slice the array once more to get the length and contents of the data:

In [32]:
len(mat_contents['results'][0][0][5][0])

104

In [33]:
mat_contents['results'][0][0][5][0]

array([ 90.05229743, 103.29464096,  52.5003051 ,  61.26043554,
        58.46970686,  65.02735765,  79.35433467,  55.52923232,
        61.65209544,  58.54636887,  58.2352045 ,  60.8580735 ,
        78.67607821,  65.83321848,  59.1036802 ,  57.24532117,
        52.21608709,  54.8938333 ,  91.72904187, 142.94101948,
        55.68445476,  51.27669459,  89.81346633,  65.30896018,
        63.86792623,  56.49889049,  53.03939731,  52.92364139,
        51.01211255,  55.28914662,  73.11066938,  53.42862127,
        51.27126211,  77.90314946,  64.05432084,  58.15988079,
        58.38398366,  78.22980443,  53.9692733 ,  75.07096897,
        49.67904216,  64.37740699,  53.99647056,  66.52730404,
        57.03675272, 104.8808961 ,  98.8686801 ,  81.81054251,
        77.9988954 ,  78.71568042, 104.72023719,  89.81327895,
        64.38890702, 117.54488381, 192.31885961, 141.18895826,
        59.55944815,  46.02413015,  91.2136864 ,  51.99716813,
       109.6810936 ,  47.17729569,  82.47509393, 105.30

In [34]:
for index in range(0, len(mat_contents['results'][0][0])):
    print('\n')
    print(index)
    print(type(mat_contents['results'][0][0][index][0]))
    print('length')
    print(len(mat_contents['results'][0][0][index][0]))
    print(mat_contents['results'].dtype.descr[index])



0
<class 'numpy.ndarray'>
length
8
('nfoot', '|O')


1
<class 'numpy.ndarray'>
length
8
('steps_tot', '|O')


2
<class 'numpy.ndarray'>
length
104
('WB_time', '|O')


3
<class 'numpy.ndarray'>
length
104
('Ngait_cycles', '|O')


4
<class 'numpy.ndarray'>
length
104
('gait_timestamps', '|O')


5
<class 'numpy.ndarray'>
length
104
('cadence_mean', '|O')


6
<class 'numpy.ndarray'>
length
104
('speed_mean', '|O')


7
<class 'numpy.ndarray'>
length
104
('speed_std', '|O')


8
<class 'numpy.ndarray'>
length
104
('slength_mean', '|O')


9
<class 'numpy.ndarray'>
length
104
('slength_std', '|O')


10
<class 'numpy.ndarray'>
length
104
('gtime_mean', '|O')


11
<class 'numpy.ndarray'>
length
104
('gtime_std', '|O')


12
<class 'numpy.ndarray'>
length
104
('speed_CV', '|O')


13
<class 'numpy.ndarray'>
length
104
('slength_CV', '|O')


14
<class 'numpy.ndarray'>
length
104
('gtime_CV', '|O')


In [35]:
os.getcwd()

'/app'

In [36]:
file_list = os.listdir('Data')
file_list_mat = [x for x in  file_list if x[-4:] == '.mat']
len(file_list_mat)

86

In [37]:
os.listdir()

['Test_Load_Transform.ipynb',
 '.DS_Store',
 'requirements.txt',
 'Untitled.ipynb',
 'Dockerfile',
 'source',
 'tests',
 'load_transform_data.ipynb',
 'docs',
 'loading_mat_file.ipynb',
 '.ipynb_checkpoints',
 'Data']

In [38]:
os.chdir('Data')

data_all = dict()

for file in file_list_mat:
    mat_contents = sio.loadmat(file)
    data_all[file] = mat_contents

In [26]:
len(data_all)

86

In [27]:
file_list_mat.sort()
file_list_mat

['Sub_01_locomotion_metrics_T2.mat',
 'Sub_01_locomotion_metrics_T3.mat',
 'Sub_02_locomotion_metrics_T2.mat',
 'Sub_02_locomotion_metrics_T3.mat',
 'Sub_03_locomotion_metrics_T2.mat',
 'Sub_03_locomotion_metrics_T3.mat',
 'Sub_05_locomotion_metrics_T2.mat',
 'Sub_05_locomotion_metrics_T3.mat',
 'Sub_06_locomotion_metrics_T2.mat',
 'Sub_06_locomotion_metrics_T3.mat',
 'Sub_07_locomotion_metrics_T2.mat',
 'Sub_07_locomotion_metrics_T3.mat',
 'Sub_08_locomotion_metrics_T2.mat',
 'Sub_08_locomotion_metrics_T3.mat',
 'Sub_09_locomotion_metrics_T2.mat',
 'Sub_09_locomotion_metrics_T3.mat',
 'Sub_10_locomotion_metrics_T2.mat',
 'Sub_10_locomotion_metrics_T3.mat',
 'Sub_13_locomotion_metrics_T2.mat',
 'Sub_13_locomotion_metrics_T3.mat',
 'Sub_14_locomotion_metrics_T2.mat',
 'Sub_14_locomotion_metrics_T3.mat',
 'Sub_15_locomotion_metrics_T2.mat',
 'Sub_15_locomotion_metrics_T3.mat',
 'Sub_16_locomotion_metrics_T2.mat',
 'Sub_16_locomotion_metrics_T3.mat',
 'Sub_17_locomotion_metrics_T2.mat',
 

In [28]:
data_all.keys()

dict_keys(['Sub_07_locomotion_metrics_T3.mat', 'Sub_21_locomotion_metrics_T2.mat', 'Sub_21_locomotion_metrics_T3.mat', 'Sub_07_locomotion_metrics_T2.mat', 'Sub_43_locomotion_metrics_T3.mat', 'Sub_34_locomotion_metrics_T3.mat', 'Sub_34_locomotion_metrics_T2.mat', 'Sub_43_locomotion_metrics_T2.mat', 'Sub_44_locomotion_metrics_T2.mat', 'Sub_15_locomotion_metrics_T3.mat', 'Sub_33_locomotion_metrics_T2.mat', 'Sub_33_locomotion_metrics_T3.mat', 'Sub_15_locomotion_metrics_T2.mat', 'Sub_44_locomotion_metrics_T3.mat', 'Sub_26_locomotion_metrics_T3.mat', 'Sub_08_locomotion_metrics_T3.mat', 'Sub_08_locomotion_metrics_T2.mat', 'Sub_26_locomotion_metrics_T2.mat', 'Sub_23_locomotion_metrics_T2.mat', 'Sub_05_locomotion_metrics_T3.mat', 'Sub_05_locomotion_metrics_T2.mat', 'Sub_23_locomotion_metrics_T3.mat', 'Sub_18_locomotion_metrics_T3.mat', 'Sub_49_locomotion_metrics_T2.mat', 'Sub_36_locomotion_metrics_T3.mat', 'Sub_10_locomotion_metrics_T2.mat', 'Sub_10_locomotion_metrics_T3.mat', 'Sub_36_locomotio

In [15]:
len(mat_contents['results'][0][0][index]

array([[ 74.53463096,  49.43887089,  28.89523238,  32.3066547 ,
         29.93984892,  30.35181787,  44.19642326,  29.90726358,
         26.40001129,  27.76033363,  27.6447679 ,  30.92535269,
         41.37948444,  19.3054391 ,  10.80069799,  27.98542923,
         14.33653145,  24.95644054,  20.94599185, 122.41027026,
          0.        ,  33.24327287,  37.5503099 ,  33.80471263,
         23.39822401,  22.99700129,  39.7866449 ,  22.775715  ,
         28.66867164,  47.92818122,  33.66925199,  39.41823738,
         26.69078442,  32.72482885,  24.96967621,  20.90838057,
         26.98778346,  45.47158412,  22.50358437,  27.61281564,
         30.32834813,  31.71021855,  26.55982608,  37.84510258,
         20.39216425,  12.66014206,  64.1746253 ,  83.53090971,
         38.10160084,  46.02211403,  47.57443464,  48.48273908,
         18.9705556 ,  26.65232278,  11.03303296,  47.24095042,
         14.73588535,  33.98398505,  50.58718342,  42.12341837,
         36.89550457,  40.1899324 ,  65.

In [17]:
len(mat_contents['results'][0][0][index][0])

104

In [52]:
round_counter = 0
for key, item in data_all.items():
    print('\n')
    print(item['results'][0][0].dtype.descr[0])
    print(len(item['results'][0][0][0][0]))
    print(item['results'][0][0].dtype.descr[1])
    print(len(item['results'][0][0][1][0]))
    print(item['results'][0][0][1][0])
    print(len(item['results'][0][0][3][0]))
    round_counter += 1
    if round_counter > 7:
        break



('nfoot', '|O')
8
('steps_tot', '|O')
8
[ 522  152 1139  754  974 1028  858    6]
162


('nfoot', '|O')
3
('steps_tot', '|O')
3
[11674  4112  5132]
438


('nfoot', '|O')
7
('steps_tot', '|O')
7
[ 4022  3530  3492  4662  4474  7108 10152]
962


('nfoot', '|O')
7
('steps_tot', '|O')
7
[794 438 378 691 587 508 516]
118


('nfoot', '|O')
7
('steps_tot', '|O')
7
[1418 1683 1459  914 1263 1860 1577]
280


('nfoot', '|O')
7
('steps_tot', '|O')
7
[5052 2610 6038 5255 1908 3931   19]
600


('nfoot', '|O')
13
('steps_tot', '|O')
13
[2461 2043 2362 3782 3730 3022 4960 3332 4545 4145 2652 3980 4055]
1213


('nfoot', '|O')
7
('steps_tot', '|O')
7
[2283 2158 1523 2133 2270 1954  133]
361
